import type { Metadata } from "next"
import { Inter } from "next/font/google"

// imports here
import "../style/globals.css"
import Navbar from "@/components/navbar/navbar"
import Sidebar from "@/components/sidebar/sidebar"
import MobileNavigation from "@/components/navbar/mobile-navigation"
import { getSideBarData } from "@/app/actions/getSideBarData"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const sideBarData = await getSideBarData()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <MobileNavigation data={sideBarData!} />

        <div className="w-full h-full flex ">
          <div className="fixed hidden md:flex inset-0 w-72 h-full  border-r  bg-white z-[50]">
            <Sidebar data={sideBarData!} />
          </div>

          {/* Pages div  */}
          <main className=" md:ml-72 w-full h-full mt-[62px]">{children}</main>
        </div>
      </body>
    </html>
  )
}
